language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'cd src'
  - 'npm install'
  - 'bower install'
  - 'gem install sass --version "=3.4.7"'
  - 'gem install compass --version "=1.0.1"'
  - 'gem install susy --version "=2.1.3"'
  - 'gem install breakpoint --version "=2.5.0"'
after_script:
  - 'npm run-script deploy'
env:
  global:
    - GH_REF: 'github.com/KoffeinFlummi/Arma3Spotter'
    - secure: 'NZfVQwI9XVj2K90wYoqVBnkjsHGu2a/+JMRvARQarMCdjid/c51GmkRYcWLgn0ezQ9+x7ad3knFdaJiT3cZgZ3bTvaZhlG+EPx848GRFIPTop+Z8HAXQNg2taIkvTLLFKUQEmpehX0offnRGe0aKm2s60XmaoZ/Hy+TcDJBq2zw='
